name: nexttoptech_assignment
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+2

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  loader_overlay: ^4.0.0
  http: ^1.2.1
  dartz: ^0.10.1
  intl: ^0.19.0
  url_launcher: ^6.3.0
  get_storage: ^2.1.1
  cached_network_image: ^3.3.1
  internet_connection_checker_plus: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true